# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e4060f673f2534c301ac463a311878d48c7eecc89d3799dd983bc30ce1f73422d606a9faf716b183ce105541eb62814e16f466826cb266c695cb614b63be3e5

test:
  secret_key_base: 4da0c26d69d8c13523f4599623540bd8b4c0f10b75c00e36dc117e6dac337d7d5428f3e02a15b8d2af679430a9d2623bfcc382c90389c5bdf8235e2ecab39fdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
